### ISSUE TITLE
这么好的项目为什么 pr 这么少呢？

### ISSUE THREAD

**Issue by HelloVass** [wingjay/jianshi#5]
我最近发现了这个 app ，觉得非常优雅，fork 之后，我在本地却无法正常导入，作者最近很忙吧，好久没有更新 gradle 的配置文件了吧！

**Comment by HelloVass** [comment]
@wingjay 我觉得有个非常需要改进的地方，那些**辑、阅**的控件响应区域太小了！！！

**Comment by wingjay** [comment]
最近在忙着写毕业论文，写完后就会继续更新啦～

**Comment by HelloVass** [comment]
@wingjay 什么时候有空，用 dagger、rxandroid、retrofit ，结合 mvp 把 jianshi 的 code 也写得和 UI 一样优雅！！！真的好喜欢这个 App
