### ISSUE TITLE
您的作品已添加至“独立开发者制作的APP集合”里

### ISSUE THREAD

**Issue by revir** [wingjay/jianshi#58]
你好，我是 V2MM 的站长，V2MM 是一个自由职业者原创网站，我正在收集中国“独立开发者制作的APP集合”， 看到您的作品，我觉得很Cool，故而添加在这个清单里，访问者可以从这个清单直接跳转到您的作品官网链接，并且大标题显示了作者和链接，如您不满意，可私信我删除，谢谢！

**Comment by revir** [comment]
忘了添加了， 清单在此：  https://v2mm.tech/category/32/collection-personal-apps

**Comment by wingjay** [comment]
可以的。
